import type { FocusLevel, NocturneData, Task } from "./types";

const subjectMap: [RegExp, string][] = [[/(수학|math|数学|數學)/i, "math"], [/(영어|english|英語|英语)/i, "english"], [/(과학|science|科学|科學)/i, "science"], [/(국어|korean|国語|语文)/i, "language"]];
const kindMap: [RegExp, string][] = [[/(문제|problem|問題|题)/i, "problems"], [/(개념|concept|概念)/i, "concept"], [/(암기|memor|暗記|记忆)/i, "memory"], [/(읽|read|読|阅读)/i, "reading"]];
export function taskSignature(title: string) { return `${subjectMap.find(([regex]) => regex.test(title))?.[1] ?? "other"}:${kindMap.find(([regex]) => regex.test(title))?.[1] ?? "work"}`; }
export function similarTasks(task: Pick<Task, "title">, candidates: Task[]) { const signature = taskSignature(task.title); return candidates.filter(item => taskSignature(item.title) === signature); }
export function feelSuggestion(title: string, history: Task[]) { const similar = similarTasks({ title }, history).filter(task => task.status === "done"); if (similar.length < 3) return null; return { interest: Math.round(similar.reduce((sum, task) => sum + task.interest, 0) / similar.length), difficulty: Math.round(similar.reduce((sum, task) => sum + task.difficulty, 0) / similar.length) }; }
export function calibratedEstimate(title: string, history: Task[], data: NocturneData) { const similar = similarTasks({ title }, history).filter(task => task.userEstimatedMinutes); if (similar.length < 3) return null; const ratios = similar.map(task => { const actual = data.sessions.filter(session => session.taskId === task.id).reduce((sum, session) => sum + session.completedMinutes, 0); return actual / Math.max(1, task.userEstimatedMinutes!); }); return ratios.reduce((sum, ratio) => sum + ratio, 0) / ratios.length; }
export function focusProfile(data: NocturneData): { bestHour: number; fadeHour: number } | null { const done = data.sessions.filter(session => session.status === "done" && session.actualEnd); const days = new Set(done.map(session => session.date)); if (done.length < 10 || days.size < 5) return null; const hours = done.map(session => new Date(session.actualEnd!).getHours()); const counts = new Map<number, number>(); hours.forEach(hour => counts.set(hour, (counts.get(hour) ?? 0) + 1)); const bestHour = [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0]; return { bestHour, fadeHour: Math.max(...hours) }; }
export function historyNudge(task: Task, hour: number, profile: ReturnType<typeof focusProfile>): number { if (!profile || task.difficulty < 4) return 0; return Math.abs(hour - profile.bestHour) <= 1 ? 2 : 0; }
export function focusFromSessions(data: NocturneData): FocusLevel { const profile = focusProfile(data); return profile ? "sharp" : "steady"; }
